<#
.SYNOPSIS
    Toolchain-agnostic core for the Denoizinator plugins.

.DESCRIPTION
    SOURCE OF TRUTH. Do not edit the copies under
    plugins/*/scripts/vendor/ -- they are generated by scripts/Sync-Shared.ps1
    and CI fails if they drift from this file.

    The contract every toolchain wrapper implements:

      1. Run the underlying build/test command with full output redirected
         to files under the repo's .dnz/ directory.
      2. Emit ONLY actionable diagnostics on stdout: errors, test failures,
         and a one-line summary.
      3. Never deny a command. Clamp, never deny -- a denial costs an
         assistant turn plus permanent context growth from both the denial
         and the retry.
      4. Preserve the underlying exit code.
#>

Set-StrictMode -Version Latest

function Get-DnzOutputDirectory {
    [CmdletBinding()]
    param(
        [string] $RepoRoot = (Get-Location).Path
    )
    $dir = Join-Path $RepoRoot '.dnz'
    if (-not (Test-Path -LiteralPath $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
    return $dir
}

function Write-DnzSummary {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [string]   $Headline,
        [string[]] $Diagnostics = @(),
        [string]   $EvidencePath,
        [int]      $MaxDiagnostics = 20
    )

    Write-Output $Headline

    if ($Diagnostics.Count -gt 0) {
        $shown = $Diagnostics | Select-Object -First $MaxDiagnostics
        $shown | ForEach-Object { Write-Output $_ }

        $omitted = $Diagnostics.Count - $shown.Count
        if ($omitted -gt 0) {
            Write-Output "... $omitted more (see $EvidencePath)"
        }
    }

    if ($EvidencePath) {
        Write-Output "evidence: $EvidencePath"
    }
}

Export-ModuleMember -Function Get-DnzOutputDirectory, Write-DnzSummary
