<#
.SYNOPSIS
    dotnet-test-specific logic for the Phase 4 wrapper: runner detection,
    per-runner-per-TFM flag selection, TRX parsing, and summary formatting.

.DESCRIPTION
    SOURCE OF TRUTH. Do not edit the copy under
    plugins/denoizinator-net/scripts/vendor/ -- it is generated by
    scripts/Sync-Shared.ps1 and CI fails if it drifts from this file.

    Every flag choice here traces to docs/dotnet-test-runner-findings.md --
    see docs/denoizinator-net-spec.md §6 Phase 4 before changing any of it.
    In particular: VSTest's quiet console output carries counts only, so
    failure detail comes from a requested TRX; MTP's console output already
    carries failure detail inline, so MTP never requests a TRX, and
    --report-trx must never be added to an MTP invocation (NUnit-MTP and
    xunit.v3-MTP reject it with exit 5 and zero tests run). The MTP progress
    flag is chosen per runner+TFM, never one flag for all of MTP -- see the
    matrix in Get-DotnetTestInvocationPlan.
#>

Set-StrictMode -Version Latest

function Get-DotnetTestRunnerInfo {
    <#
    .SYNOPSIS
        Static, read-only detection of which test runner+framework+TFM a
        project uses -- never writes global.json, never invokes dotnet.
        Mirrors probes/Probe-DotnetTest.ps1's Get-DetectedRunner, extended to
        also report which framework matched (needed for the progress-flag
        matrix) and the project's TargetFramework.
    #>
    [CmdletBinding()]
    param([Parameter(Mandatory)][string] $ProjectPath)

    $content = Get-Content -LiteralPath $ProjectPath -Raw

    $globalJsonText = $null
    $dir = (Get-Item -LiteralPath $ProjectPath).Directory
    while ($dir -and -not $globalJsonText) {
        $candidate = Join-Path $dir.FullName 'global.json'
        if (Test-Path -LiteralPath $candidate) { $globalJsonText = Get-Content -LiteralPath $candidate -Raw }
        $dir = $dir.Parent
    }

    $runner = 'Unknown'
    if ($globalJsonText -match 'Microsoft\.Testing\.Platform') {
        $runner = 'MTP'
    } elseif ($content -match 'EnableMSTestRunner|UseMicrosoftTestingPlatform|EnableNUnitRunner|EnableXunitRunner') {
        $runner = 'MTP'
    } elseif ($content -match 'Include="xunit\.v3"') {
        $runner = 'MTP'
    } elseif ($content -match 'Include="Microsoft\.Testing\.') {
        $runner = 'MTP'
    } elseif ($content -match 'Include="MSTest"' -or $content -match 'Include="Microsoft\.NET\.Test\.Sdk"') {
        $runner = 'VSTest'
    }

    # Order matters: 'xunit.v3' must be tested before the plain 'xunit' check
    # since a naive substring match on 'xunit' would also hit 'xunit.v3'.
    $framework = $null
    if     ($content -match 'Include="xunit\.v3"') { $framework = 'xunit.v3' }
    elseif ($content -match 'Include="xunit"')     { $framework = 'xunit' }
    elseif ($content -match 'Include="NUnit"')     { $framework = 'NUnit' }
    elseif ($content -match 'Include="MSTest')     { $framework = 'MSTest' }

    $tfmMatch = [regex]::Match($content, '<TargetFramework>([^<]+)</TargetFramework>')
    $tfm = if ($tfmMatch.Success) { $tfmMatch.Groups[1].Value } else { $null }

    return [pscustomobject]@{ Runner = $runner; Framework = $framework; Tfm = $tfm }
}

function Resolve-DotnetTestProject {
    <#
    .SYNOPSIS
        Resolve the project a 'dotnet test <TestArgs>' invocation targets,
        the same way `dotnet test` itself would: an explicit --project value,
        or a project/solution path as the first (pre-option) positional
        argument, or -- if neither was given -- the single *.csproj in
        -WorkingDirectory. Returns $null when resolution is ambiguous (a
        .sln, multiple csproj files, or a missing explicit path) rather than
        guessing.
    #>
    [CmdletBinding()]
    param(
        [string[]] $TestArgs = @(),
        [Parameter(Mandatory)][string] $WorkingDirectory
    )

    for ($i = 0; $i -lt $TestArgs.Count; $i++) {
        if ($TestArgs[$i] -eq '--project' -and ($i + 1) -lt $TestArgs.Count) {
            $candidate = $TestArgs[$i + 1]
            if (-not [System.IO.Path]::IsPathRooted($candidate)) {
                $candidate = Join-Path $WorkingDirectory $candidate
            }
            if (Test-Path -LiteralPath $candidate) { return (Resolve-Path -LiteralPath $candidate).Path }
            return $null
        }
    }

    # dotnet test's own grammar: a project/solution path, if given, must be
    # the very first token, before any options.
    if ($TestArgs.Count -gt 0 -and -not $TestArgs[0].StartsWith('-') -and $TestArgs[0] -match '\.(csproj|sln|slnx)$') {
        $candidate = $TestArgs[0]
        if (-not [System.IO.Path]::IsPathRooted($candidate)) {
            $candidate = Join-Path $WorkingDirectory $candidate
        }
        if (Test-Path -LiteralPath $candidate) { return (Resolve-Path -LiteralPath $candidate).Path }
        return $null
    }

    $csprojCandidates = @(Get-ChildItem -LiteralPath $WorkingDirectory -Filter '*.csproj' -File -ErrorAction SilentlyContinue)
    if ($csprojCandidates.Count -eq 1) { return $csprojCandidates[0].FullName }

    return $null
}

function Get-DotnetTestInvocationPlan {
    <#
    .SYNOPSIS
        The per-runner-per-TFM flag matrix as data, in one place. Returns the
        ADDITIONAL args to append to the caller's original 'dotnet test
        <TestArgs>' invocation -- never a full replacement argv, so the
        caller's own args (--filter, etc.) are always preserved untouched.

        Mode = 'Passthrough' means: do not attempt to normalise at all (no
        known-safe flag exists yet, e.g. xunit.v3-MTP, or the project type
        wasn't recognised). Mode = 'Normalize' means AdditionalArgs is safe
        to append.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string] $Runner,
        [string] $Framework,
        [string] $Tfm,
        [Parameter(Mandatory)][string] $DnzDir
    )

    if ($Runner -eq 'Unknown' -or ($Runner -eq 'MTP' -and $Framework -eq 'xunit.v3')) {
        return [pscustomobject]@{ Mode = 'Passthrough'; InvokeVia = $null; AdditionalArgs = @(); UsesTrx = $false; TrxPath = $null; OutputShape = $null }
    }

    # VSTest's quiet console output is counts-only (dotnet-test-runner-
    # findings.md §5) -- a TRX is the only source of failure detail.
    $vstestTrxPath = Join-Path $DnzDir 'test.trx'
    $vstestArgs    = @('--nologo', '-v:q', '--logger', 'trx;LogFileName=test.trx', '--results-directory', $DnzDir)
    $vstestPlan    = [pscustomobject]@{ Mode = 'Normalize'; InvokeVia = 'DotnetTest'; AdditionalArgs = $vstestArgs; UsesTrx = $true; TrxPath = $vstestTrxPath; OutputShape = 'VSTest' }

    if ($Runner -eq 'VSTest') { return $vstestPlan }

    if ($Runner -eq 'MTP') {
        # NEVER --report-trx here: NUnit-MTP and xunit.v3-MTP reject it with
        # exit 5 and zero tests run (findings §7). MTP's console output
        # already carries failure detail inline, so it isn't needed anyway.
        $tfmText = if ($Tfm) { $Tfm } else { '' }
        $majorMatch = [regex]::Match($tfmText, '^net(\d+)')
        $major = if ($majorMatch.Success) { [int]$majorMatch.Groups[1].Value } else { 0 }

        # net6.0 MSTest-MTP silently bridges to the VSTest ENGINE at runtime
        # under plain 'dotnet test' (findings §6 -- the 'S=0' count-tuple
        # tell) -- confirmed by hand that MTP-native flags like --no-progress
        # are UNRECOGNISED there ("Unknown switch", exit 1) since the bridge
        # is genuinely VSTest underneath; it needs VSTest's own flags instead,
        # identical to the $vstestPlan above. Every other MTP combination
        # measured (MSTest net8.0/net10.0, NUnit any tested TFM) gives a
        # wrong-runner MSBuild error under plain 'dotnet test' with no
        # global.json -- confirmed by hand for both. Since the wrapper must
        # never write global.json (findings §9), those must be invoked via
        # the project's own BUILT EXECUTABLE directly instead, per findings
        # §9's wrapper recipe.
        if ($Framework -eq 'MSTest' -and $major -lt 8) { return $vstestPlan }

        # findings §12: '--progress off' works cleanly ONLY on MSTest-MTP
        # net8.0/net10.0. It is rejected (exit 5, ~4x baseline) by MSTest-MTP
        # net6.0 (handled above) and by NUnit-MTP -- both fall back to the
        # deprecated but functional '--no-progress'.
        $progressArgs =
            if ($Framework -eq 'MSTest' -and $major -ge 8) { @('--progress', 'off', '--no-ansi') }
            else                                            { @('--no-progress', '--no-ansi') }

        return [pscustomobject]@{ Mode = 'Normalize'; InvokeVia = 'Executable'; AdditionalArgs = $progressArgs; UsesTrx = $false; TrxPath = $null; OutputShape = 'MTP' }
    }

    return [pscustomobject]@{ Mode = 'Passthrough'; InvokeVia = $null; AdditionalArgs = @(); UsesTrx = $false; TrxPath = $null; OutputShape = $null }
}

function Resolve-DotnetTestExecutable {
    <#
    .SYNOPSIS
        Locate the project's own built test-host executable, for the MTP
        InvokeVia='Executable' case. Tries the conventional
        bin/<Configuration>/<Tfm>/<ProjectFileBaseName>.exe path first (true
        for every project this repo's probes scaffold); falls back to the
        newest *.exe under bin/ matching that base name, in case AssemblyName
        was overridden or the TFM/Configuration guess was wrong. Returns
        $null -- never throws -- when nothing is found, so the caller can
        fall back to a build attempt or passthrough.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string] $ProjectPath,
        [string] $Tfm,
        [string] $Configuration = 'Debug'
    )

    $projectDir = Split-Path -Parent $ProjectPath
    $baseName   = [System.IO.Path]::GetFileNameWithoutExtension($ProjectPath)
    $binDir     = Join-Path $projectDir 'bin'

    if ($Tfm) {
        $direct = Join-Path $binDir "$Configuration\$Tfm\$baseName.exe"
        if (Test-Path -LiteralPath $direct) { return $direct }
    }

    if (-not (Test-Path -LiteralPath $binDir)) { return $null }
    $candidates = @(Get-ChildItem -LiteralPath $binDir -Recurse -Filter "$baseName.exe" -File -ErrorAction SilentlyContinue)
    if ($candidates.Count -gt 0) {
        return ($candidates | Sort-Object -Property LastWriteTime -Descending | Select-Object -First 1).FullName
    }
    return $null
}

function ConvertFrom-VSTestTrx {
    <#
    .SYNOPSIS
        Extract counts and per-failure name/message detail from a VSTest TRX
        file. The TRX root carries an xmlns -- every query here goes through
        an XmlNamespaceManager, or it silently matches nothing.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string] $TrxPath,
        [int] $MaxFailures = 5
    )

    [xml]$xml = Get-Content -LiteralPath $TrxPath -Raw
    $ns = [System.Xml.XmlNamespaceManager]::new($xml.NameTable)
    $ns.AddNamespace('t', 'http://microsoft.com/schemas/VisualStudio/TeamTest/2010')

    $counters = $xml.SelectSingleNode('//t:ResultSummary/t:Counters', $ns)
    $total  = if ($counters -and $counters.total)  { [int]$counters.total }  else { 0 }
    $passed = if ($counters -and $counters.passed) { [int]$counters.passed } else { 0 }
    $failed = if ($counters -and $counters.failed) { [int]$counters.failed } else { 0 }

    $testDefs = @{}
    foreach ($unitTest in $xml.SelectNodes('//t:TestDefinitions/t:UnitTest', $ns)) {
        $method = $unitTest.TestMethod
        if ($unitTest.id -and $method) {
            $shortClassName = $method.className -replace ',.*$', ''
            $testDefs[$unitTest.id] = "$shortClassName.$($method.name)"
        }
    }

    $failures = [System.Collections.Generic.List[object]]::new()
    foreach ($result in $xml.SelectNodes('//t:Results/t:UnitTestResult', $ns)) {
        if ($result.outcome -ne 'Failed') { continue }

        $name = if ($result.testId -and $testDefs.ContainsKey($result.testId)) { $testDefs[$result.testId] } else { $result.testName }

        $message = $null
        $msgNode = $result.SelectSingleNode('t:Output/t:ErrorInfo/t:Message', $ns)
        if ($msgNode -and $msgNode.InnerText) {
            $firstLine = @($msgNode.InnerText -split "`n" | Where-Object { $_.Trim() })[0]
            $message = if ($firstLine) { $firstLine.Trim() } else { $msgNode.InnerText.Trim() }
        }
        if (-not $message) { $message = '(no failure message)' }

        $failures.Add([pscustomobject]@{ TestName = $name; Message = $message })
    }

    $shown = @($failures | Select-Object -First $MaxFailures)

    return [pscustomobject]@{
        Total                = $total
        Passed               = $passed
        Failed               = $failed
        Skipped              = [Math]::Max(0, $total - $passed - $failed)
        Failures             = $shown
        OmittedFailureCount  = [Math]::Max(0, $failures.Count - $shown.Count)
    }
}

function Get-VSTestOutcome {
    <#
    .SYNOPSIS
        Classify a VSTest-engine invocation's captured output into the
        wrapper's Pass|Fail|None|Unknown vocabulary. Shared by
        Invoke-QuietDotnetTest.ps1 (dotnet test's VSTest path) and
        Invoke-QuietVstestConsole.ps1 (Framework vstest.console.exe) --
        confirmed against probes/evidence/framework-build-results.json that
        both produce byte-identical VSTest summary-line shapes under their
        respective quiet flags, so one parser correctly serves both.

    .DESCRIPTION
        Zero-tests-ran is detected by absence of a 'Passed!'/'Failed!'
        summary line, never by exit code -- every VSTest configuration
        returns exit 0 in that case (docs/dotnet-test-runner-findings.md §4).

        Two distinct zero-tests-ran signatures both normalise to 'None', but
        are classified into a NoneReason for wrapper diagnostics
        (docs/framework-build-findings.md §5):
          - 'Additionally, path to test adapters ...' / 'No test is
            available in ...' -- a packages.config project whose restore
            never wired the test adapter (nuget.exe restore doesn't do what
            PackageReference restore does). The 'Additionally, path to test
            adapters' trailer survives /logger:"console;verbosity=quiet" even
            though the message's own leading sentence is suppressed by it.
          - anything else with no summary line -- default assumed to be a
            filter matching nothing, the Phase 4 default.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][AllowEmptyString()][string] $Stdout,
        [Parameter(Mandatory)][int] $ExitCode,
        [string] $TrxPath,
        [int] $MaxFailures = 5
    )

    $result = [pscustomobject]@{
        Outcome              = $null   # Pass | Fail | None | Unknown
        Passed               = 0
        Failed               = 0
        Skipped              = 0
        NoneReason           = $null
        Failures             = @()
        OmittedFailureCount  = 0
        TrxPath              = $null
    }

    $hasSummary = $Stdout -match '(Passed!|Failed!)'
    if ($ExitCode -eq 0 -and -not $hasSummary) {
        $result.Outcome = 'None'
        if ($Stdout -match 'Additionally, path to test adapters' -or $Stdout -match 'No test is available in') {
            $result.NoneReason = 'test adapter not registered'
        } else {
            $result.NoneReason = 'filter matched nothing'
        }
        return $result
    }

    if ($Stdout -match 'Failed:\s*(\d+),\s*Passed:\s*(\d+),\s*Skipped:\s*(\d+),\s*Total:\s*(\d+)') {
        $result.Failed  = [int]$Matches[1]
        $result.Passed  = [int]$Matches[2]
        $result.Skipped = [int]$Matches[3]
        if ($result.Failed -gt 0) {
            $result.Outcome = 'Fail'
            if ($TrxPath -and (Test-Path -LiteralPath $TrxPath)) {
                $trx = ConvertFrom-VSTestTrx -TrxPath $TrxPath -MaxFailures $MaxFailures
                $result.Failures            = $trx.Failures
                $result.OmittedFailureCount = $trx.OmittedFailureCount
                $result.TrxPath             = $TrxPath
            }
        } else {
            $result.Outcome = 'Pass'
        }
    } else {
        $result.Outcome = 'Unknown'
    }

    return $result
}

function Get-VstestConsolePassthroughTrigger {
    <#
    .SYNOPSIS
        vstest.console.exe's own flag syntax is '/Name:value' -- a single,
        colon-attached token -- not '--name value' (separate array elements)
        like dotnet test. Get-DotnetTestPassthroughTrigger's exact-element
        match doesn't apply; this checks a case-insensitive PREFIX of each
        whole token instead, so '/TestCaseFilter:...~logger' or
        '/TestAdapterPath:C:\logger' never false-positively match via
        substring search the way a naive check on raw text would.

        Only two trigger prefixes are needed (fewer than dotnet test's four):
        vstest.console.exe has no '--'-passthrough convention (that's
        specific to the dotnet CLI's outer/inner argv split) and no separate
        TRX-request flag -- '/logger:trx;...' is already covered by
        '/logger:'.
    #>
    [CmdletBinding()]
    param([string[]] $TestArgs = @())

    foreach ($tok in $TestArgs) {
        foreach ($p in @('/logger:', '/resultsdirectory:')) {
            if ($tok.StartsWith($p, [System.StringComparison]::OrdinalIgnoreCase)) {
                return $p.TrimEnd(':')
            }
        }
    }
    return $null
}

function Get-DotnetTestPassthroughTrigger {
    <#
    .SYNOPSIS
        Returns the name of the first user-supplied test-host flag that
        forces passthrough (the wrapper never layers its own flags on top of
        flags the user already specified -- see
        docs/denoizinator-net-spec.md §6 Phase 4's passthrough contract), or
        $null if none is present.

        Checked against the ALREADY-TOKENIZED argument array -- one shell
        token per element, quoting already resolved by the caller's shell --
        so '--filter "Name~logger"' and '--filter "A -- B"' are each a
        single array element and never false-positively match '--logger' or
        a bare '--' via substring/regex matching against raw text.
    #>
    [CmdletBinding()]
    param([string[]] $TestArgs = @())

    foreach ($trigger in @('--logger', '--results-directory', '--report-trx', '--')) {
        if ($TestArgs -contains $trigger) { return $trigger }
    }
    return $null
}

function Format-DnzTestSummary {
    <#
    .SYNOPSIS
        The wire format for the wrapper's output, per
        docs/denoizinator-net-spec.md §6 Phase 4, extended with the TEST RAW
        (passthrough) and TEST UNKNOWN (undetermined outcome) cases from the
        exit-code/passthrough contract in that section.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][ValidateSet('Pass', 'Fail', 'None', 'Unknown', 'Raw')] [string] $Status,
        [int]      $Passed = 0,
        [int]      $Failed = 0,
        [int]      $Skipped = 0,
        [double]   $DurationSeconds = 0,
        [int]      $RawExitCode,
        [string]   $TrxPath,
        [string]   $Reason,
        [object[]] $Failures = @(),
        [int]      $OmittedFailureCount = 0
    )

    $lines = [System.Collections.Generic.List[string]]::new()
    $durationText = '{0:0.0}s' -f $DurationSeconds

    switch ($Status) {
        'Pass' {
            $lines.Add("TEST PASS | $Passed passed | $Skipped skipped | $durationText")
        }
        'Fail' {
            $trxSuffix = if ($TrxPath) { " | $TrxPath" } else { '' }
            $lines.Add("TEST FAIL | $Passed passed | $Failed failed | $durationText$trxSuffix")
            foreach ($f in $Failures) {
                $lines.Add("  $($f.TestName) — $($f.Message)")
            }
            if ($OmittedFailureCount -gt 0) {
                $lines.Add("  [+$OmittedFailureCount more]")
            }
        }
        'None' {
            $noneReason = if ($Reason) { $Reason } else { 'filter matched nothing' }
            $lines.Add("TEST NONE | 0 tests ran | $noneReason")
        }
        'Unknown' {
            $lines.Add("TEST UNKNOWN | could not determine outcome | runner exit $RawExitCode")
        }
        'Raw' {
            $lines.Add("TEST RAW | $Reason | runner exit $RawExitCode")
        }
    }

    return $lines.ToArray()
}

Export-ModuleMember -Function Get-DotnetTestRunnerInfo, Resolve-DotnetTestProject,
                              Get-DotnetTestInvocationPlan, Resolve-DotnetTestExecutable,
                              ConvertFrom-VSTestTrx, Get-DotnetTestPassthroughTrigger,
                              Get-VSTestOutcome, Get-VstestConsolePassthroughTrigger,
                              Format-DnzTestSummary
